#-------------------------------------------------------------------------------
# Makefile
# ライブラリ用メイクファイル
#
# Gakimaru's researched and standard library for C++ - GASHA
#   Copyright (c) 2014 Itagaki Mamoru
#   Released under the MIT license
#     https://github.com/gakimaru/gasha_proj/blob/master/LICENSE
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------

# ターゲット：all
all :
	cd ../sub/gasha_src/proj; \
	make all

# ターゲット：clean
clean :
	cd ../sub/gasha_src/proj; \
	make clean

# ターゲット：distclean
distclean :
	cd ../sub/gasha_src/proj; \
	make distclean

# 擬似ターゲット設定
.PHONY: all clean

#-------------------------------------------------------------------------------

# End of file
